# Generated by Django 3.1.4 on 2021-03-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyTaskAPI', '0002_remove_generaltask_programmed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignedtask',
            name='realizationTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asignedtask',
            name='state',
            field=models.IntegerField(),
        ),
    ]
